[Java] Adding profile picture need rework
Countly/countly-sdk-java pull request #128
Opened 2023-10-24 12:33 UTC by arifBurakDemiray

2023-10-24 14:59 UTC, ArtursKadikis requested changes
revert url part

2023-10-26 07:07 UTC, arifBurakDemiray commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Java] Adding profile picture need rework](https://trello.com/c/huahE7mf/1002-java-adding-profile-picture-need-rework)

2023-10-26 11:43 UTC, ArtursKadikis requested changes
if picture bytes or the picture url is set to "null" or empty string, trying to indicate that the picture should be erased from the server side, we should be sending 'picture=NULL '

2023-10-26 11:43 UTC, ArtursKadikis commented on sdk-java/src/test/java/ly/count/sdk/java/internal/UserEditorTests.java
> +        validatePictureInRQ("{\"picturePath\":\"" + imgFile.getAbsolutePath() + "\"}", imgFile.getAbsolutePath());
picture path should not be set in the user profile body

2023-10-26 11:43 UTC, ArtursKadikis commented on sdk-java/src/test/java/ly/count/sdk/java/internal/UserEditorTests.java
> +        validatePictureInRQ("{\"picturePath\":\"" + imgFile.getAbsolutePath() + "\"}", imgFile.getAbsolutePath());
it should have the mandatory params but no user profile things

2023-10-31 13:43 UTC, merged