[Java] Stop storing the config object and add a migration to delete its old file
Countly/countly-sdk-java pull request #152
Opened 2023-11-03 13:13 UTC by arifBurakDemiray

2023-11-03 13:42 UTC, arifBurakDemiray commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Java] Stop storing the config object and add a migration to delete its old file](https://trello.com/c/4T9jcdTY/847-java-stop-storing-the-config-object-and-add-a-migration-to-delete-its-old-file)

2023-11-06 09:24 UTC, ArtursKadikis requested changes
There should be test cases for both device ID type

2023-11-06 09:24 UTC, ArtursKadikis commented on sdk-java/src/main/java/ly/count/sdk/java/internal/MigrationHelper.java
> +            Files.delete(configFile.toPath());
we want to delete the file even if there was a exception

2023-11-06 09:24 UTC, ArtursKadikis commented on CHANGELOG.md
> +* Config storage is deleted, only device id and device id type are stored now
b etter entry

2023-11-07 14:00 UTC, ArtursKadikis requested changes
Missing a test case for when a custom device Id is being provided

2023-11-07 14:07 UTC, merged